### ISSUE TITLE
Backward pass runtime degradation (Linear + `tensor_product`) in the latest versions

### ISSUE THREAD

**Issue by gerkone** [e3nn/e3nn-jax#38]
Hey. The `tensor_product` implementation has changed substantially from `0.17.3` to `0.19.3`, which made it simpler and much faster in inference. This does not seem to be the case for backpropagation (especially at high Ls). I noticed this while training segnn with `L=3` on a problem that used to take hours with `e3nn-jax 0.17.3`, but with `0.19.3` did not finish in days.

Model init and backward jitting also always take a lot of time, which is not a big deal in practice but could mean something.

![e3nn-jax version vs Backprop time](https://github.com/e3nn/e3nn-jax/assets/35970687/3b0b0ce8-3ea3-423e-9569-e2123952cd9f)

On the other hand, differentiating `tensor_product` only (without linear layer) is about the same/faster in the newer versions, which is unexpected.

![e3nn-jax version vs Backprop time (tp only)](https://github.com/e3nn/e3nn-jax/assets/35970687/ada630da-2fa1-4e48-8d54-8a5e57cea960)

---

Detailed results in table. Forward and backward are 100 (compiled) passes on single Linear + `tensor_product` layer, with the spherical harmonics at the respective order as input and `1x0e + 1x1o` as output. Jit time refers to the backward pass jitting.
<table>
<thead>
  <tr>
    <th></th>
    <th colspan="3">L=0</th>
    <th colspan="3">L=3</th>
    <th colspan="3">L=5</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td></td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
  </tr>
  <tr>
    <td>0.17.3</td>
    <td>16.63</td>
    <td>10.70</td>
    <td>397.70</td>
    <td>30.32</td>
    <td>27.91</td>
    <td>751.56</td>
    <td>57.19</td>
    <td>80.14</td>
    <td>1232.86</td>
  </tr>
  <tr>
    <td>0.19.1</td>
    <td>15.14</td>
    <td>22.61</td>
    <td>747.90</td>
    <td>32.16</td>
    <td>500.49</td>
    <td>5220.34</td>
    <td>52.06</td>
    <td>1275.34</td>
    <td>34265.00</td>
  </tr>
  <tr>
    <td>0.19.2</td>
    <td>16.19</td>
    <td>35.12</td>
    <td>1123.24</td>
    <td>26.00</td>
    <td>499.58</td>
    <td>8296.36</td>
    <td>43.45</td>
    <td>2113.12</td>
    <td>60620.00</td>
  </tr>
</tbody>
</table>

Reproduction script
```python
import os
import jax
import jax.numpy as jnp 
import time
import haiku as hk
import warnings
from multiprocessing import Process, Queue

warnings.filterwarnings("ignore")


def tp_test(queue):
    import e3nn_jax as e3nn

    def run(tp_fn, ir, bs=100, reruns=100):    
        x = e3nn.normal(ir, key=jax.random.PRNGKey(0), leading_shape=(bs,))

        st = time.perf_counter_ns()
        tp = hk.without_apply_rng(hk.transform(tp_fn))
        w = tp.init(jax.random.PRNGKey(0), x)
        apply = jax.jit(tp.apply)
        jax.block_until_ready(apply(w, x))
        init_end = (time.perf_counter_ns() - st) / 1e6

        st = time.perf_counter_ns()
        for _ in range(reruns):
            jax.block_until_ready(apply(w, x))
        forward_end = (time.perf_counter_ns() - st) / 1e6

        # backwards
        @jax.jit
        def grad_fn(x):
            def loss_fn(x):
                return jnp.mean(apply(w, x))
            return jax.grad(loss_fn)(x)

        st = time.perf_counter_ns()
        jax.block_until_ready(grad_fn(x))
        jit_end = (time.perf_counter_ns() - st) / 1e6

        st = time.perf_counter_ns()
        for _ in range(reruns):
            jax.block_until_ready(grad_fn(x))
        backward_end = (time.perf_counter_ns() - st) / 1e6
        
        return forward_end, backward_end, init_end, jit_end


    print(f"Version {e3nn.__version__}")

    results = {}

    for L in [1, 3, 5]:
        ir_L = e3nn.Irreps.spherical_harmonics(L) * 8
        def only_tp(x):
            return e3nn.tensor_product(x, x, filter_ir_out="1x0e+1x1o").array
        
        frwd_time, bkwd_time, init_time, jit_time = run(only_tp, ir_L)
        print(
            f"[L={L} TP only]: forward={frwd_time:.2f}ms (init={init_time:.2f}ms) - "
            f"backward={bkwd_time:.2f}ms (jit={jit_time:.2f}ms)"
        )
                
        def linear_tp(x):
            return e3nn.haiku.Linear("1x0e+1x1o")(e3nn.tensor_product(x, x)).array
        
        frwd_time, bkwd_time, init_time, jit_time = run(linear_tp, ir_L)
        print(
            f"[L={L} Linear TP]: forward={frwd_time:.2f}ms (init={init_time:.2f}ms) - "
            f"backward={bkwd_time:.2f}ms (jit={jit_time:.2f}ms)"
        )

        results[f"L={L}"] = bkwd_time
    
    queue.put({e3nn.__version__: results})


if __name__ == "__main__":

    queue = Queue()

    os.system("pip install e3nn-jax==0.17.3 >/dev/null 2>&1")
    p = Process(target=tp_test, args=(queue,))
    p.start()
    p.join()

    print("---")

    os.system("pip install e3nn-jax==0.19.1 >/dev/null 2>&1")
    p = Process(target=tp_test, args=(queue,))
    p.start()
    p.join()

    print("---")

    os.system("pip install e3nn-jax==0.19.2 >/dev/null 2>&1")
    p = Process(target=tp_test, args=(queue,))
    p.start()
    p.join()

    try:
        import matplotlib.pyplot as plt
        import pandas as pd
        results = {}
        while not queue.empty():
            results.update(queue.get())
        results = pd.DataFrame(results)
        results.plot.bar()
        plt.title("Backward time (Linear + tensor_product only)")
        plt.ylabel("time [ms]")
        plt.savefig("e3nn_backward.png")
    
    except ImportError:
        pass
```

**Comment by ameya98** [comment]
Thanks! I believe we are also seeing some runtime differences in some other applications. We will get back to you soon.

**Comment by mariogeiger** [comment]
The slowdown in the backward pass and in the compilation time between 0.17.3 and 0.19.1 is due to the changes in `IrrepsArray` introduced in [0.19.0](https://github.com/e3nn/e3nn-jax/releases/tag/0.19.0).

Before 0.19.0, IrrepsArray was storing the data in both a contiguous array and a list of chunks (for instance `16x0e + 32x1o` has two chunks so we would have a contiguous array `(112,)` and a list of arrays `[(16, 1), (32, 3)]`). This was somehow helping the compiler for the backward pass.

Since 0.19.0, IrrepsArray only has the contiguous array and the chunks are recreated on the fly. For some reason jit does not like that.

I will try to investigate further.

**Comment by mariogeiger** [comment]
I see that in your tests you take the derivative wrt x, do you get the same slowdown if you take the derivative wrt w?
Can you also try what happens if you provide w as an argument to `grad_fn`? i.e. `grad_fn(w, x)`
Just out of curiosity.

**Comment by mariogeiger** [comment]
I found something relevant. In your test you are taking the derivative wrt x.

```python
# backwards
@jax.jit
def grad_fn(x):
    def loss_fn(x):
        return jnp.mean(apply(w, x))
    return jax.grad(loss_fn)(x)
```

If you take a derivative wrt to w, at least on my cpu, the new versions are not slower. Can you try on your gpu?

**Comment by mariogeiger** [comment]
@gerkone please try now with version `0.20.0`

**Comment by gerkone** [comment]
Hey @mariogeiger thanks for your replies. I ran a couple of things, here's what I found

## Script posted in [first comment](https://github.com/e3nn/e3nn-jax/issues/38#issue-1817769241)

### `Linear` + `tensor_product` (backward wrt x)
For completeness here is the updated plot with version `0.20.0`. It definitely looks better than before, but still slower than `0.17.3`.

![image](https://github.com/e3nn/e3nn-jax/assets/35970687/8b74ff34-0a22-4c1a-917c-450fa3769d14)

### `Linear` + `tensor_product` (backward  wrt params)

I also tried taking the derivative wrt the weights, and indeed runtimes are similar through all versions. __Jit times are still very high though__; here is the plot and table (with derivatives wrt params as well).

The results are unexpected to me, and even taking your explanation into account I can't really find a reason. 

![image](https://github.com/e3nn/e3nn-jax/assets/35970687/03a1f736-c129-498e-b291-6a9bc8c4a629)

<table>
<thead>
  <tr>
    <th></th>
    <th colspan="3">L=1</th>
    <th colspan="3">L=3</th>
    <th colspan="3">L=5</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td></td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
  </tr>
  <tr>
    <td>0.17.3</td>
    <td>8.26</td>
    <td>10.10</td>
    <td>211.15</td>
    <td>20.42</td>
    <td>26.68</td>
    <td>277.30</td>
    <td>45.92</td>
    <td>62.44</td>
    <td>421.97</td>
  </tr>
  <tr>
    <td>0.19.1</td>
    <td>7.83</td>
    <td>9.48</td>
    <td>342.22</td>
    <td>21.22</td>
    <td>27.28</td>
    <td><b>1949.29</td>
    <td>49.29</td>
    <td>55.73</td>
    <td><b>15627.83</td>
  </tr>
  <tr>
    <td>0.19.2</td>
    <td>8.86</td>
    <td>10.13</td>
    <td>346.49</td>
    <td>16.19</td>
    <td>24.20</td>
    <td><b>2849.34</td>
    <td>22.59</td>
    <td>30.91</td>
    <td><b>27257.30</td>
  </tr>
  <tr>
    <td>0.20.0</td>
    <td>8.47</td>
    <td>12.93</td>
    <td>223.31</td>
    <td>14.90</td>
    <td>22.56</td>
    <td>385.46</td>
    <td>22.88</td>
    <td>28.62</td>
    <td>882.78</td>
  </tr>
</tbody>
</table>

### `tensor_product` only
Tensor product only, without a linear layer. No particular difference can be noticed here.

![image](https://github.com/e3nn/e3nn-jax/assets/35970687/376b40fc-099b-4611-ae04-94a990588209)

## [SEGNN](https://github.com/gerkone/segnn-jax)
Since this is what made me notice this originally I also wanted to see the differences in practice.
Here is again the bar plot and table on full segnn models (derivative wrt x)

![image](https://github.com/e3nn/e3nn-jax/assets/35970687/2d5133e9-5993-4502-973f-77a5bc33eeea)


<table>
<thead>
  <tr>
    <th></th>
    <th colspan="3">L=1 SEGNN</th>
    <th colspan="3">L=2 SEGNN</th>
    <th colspan="3">L=3 SEGNN</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td></td>
    <td>Fwrd</td>
    <td>Bkwd</td>
    <td>Jit</td>
    <td>Fwrd</td>
    <td>Bkwd</td>
    <td>Jit</td>
    <td>Fwrd</td>
    <td>Bkwd</td>
    <td>Jit</td>
  </tr>
  <tr>
    <td>0.17.3</td>
    <td>207.98</td>
    <td>499.78</td>
    <td>4343.33</td>
    <td>495.22</td>
    <td>1096.72</td>
    <td>9955.54</td>
    <td>937.68</td>
    <td>2297.58</td>
    <td>17534.29</td>
  </tr>
  <tr>
    <td>0.19.1</td>
    <td>183.45</td>
    <td>787.24</td>
    <td>10061.65</td>
    <td>481.54</td>
    <td>2321.90</td>
    <td>28145.21</td>
    <td>924.88</td>
    <td>7307.63</td>
    <td>67915.30</td>
  </tr>
  <tr>
    <td>0.19.2</td>
    <td>436.03</td>
    <td>1165.99</td>
    <td>17921.59</td>
    <td>615.51</td>
    <td>2520.09</td>
    <td>35293.16</td>
    <td>1116.62</td>
    <td>7734.88</td>
    <td>100226.55</td>
  </tr>
  <tr>
    <td>0.20.0</td>
    <td>469.82</td>
    <td>1011.10</td>
    <td>10210.34</td>
    <td>614.72</td>
    <td>1818.22</td>
    <td>18612.05</td>
    <td>1214.80</td>
    <td>3473.40</td>
    <td>39235.92</td>
  </tr>
</tbody>
</table>


Backward (and jit) times get worse after version `0.17.3` (they blow up at higher orders) as expected, but only improve in terms of scaling to higher Ls with version `0.20.0`. Additionally, forward times seem to also have gotten worse with newer versions. 

This is more or less in line with what I got with the test script (it better be; in the end segnn is just a stack of parametrized tensor products).

---

I agree that looking throughout the latest releases the major change is the lazy chunks in the `IrrepArray`, and reverting it with both contiguous and chunked representation does actually help on higher orders (probably because the contiguous array is larger/has more chunks). On the other hand (assuming I didn't make any mistakes) it looks like there is something else going on, maybe unrelated to the `IrrepsArray`, but I can't find what it could be.

I also have a couple of ideas of benchmarking `IrrepsArray` creation/rechunking and operations but I still haven't gotten to it. In case I manage something I'll let you know.

I hope this is somehow useful, and thanks for the latest release which already improved runtimes significantly.

**Comment by mariogeiger** [comment]
Thanks a lot!

- Can you add `0.20.1` in the benchmark? [several optimizations have been added back in this release](https://github.com/e3nn/e3nn-jax/compare/0.20.0...0.20.1)
- Do you believe `Linear + tensor_product (backward wrt x)` is a good proxy for `SEGNN backward` ?

**Comment by gerkone** [comment]
Sure, here's the updated plot/table with version `0.20.1`, and it indeed looks like you are right! Now it's looking much better already. Still, a couple of this I noticed are
- __L=1 forward time did not improve upon `0.19.2`__, while on larger Ls it's even faster than `0.17.3`.
- Compile times are still larger than previously, but I think that's less of a concern.

I didn't include it at first because the latest version is [`0.20.0` on PyPi](https://pypi.org/project/e3nn-jax/), so I had to install it with `pip install git+https://github.com/e3nn/e3nn-jax.git@0.20.1`. 

![image](https://github.com/e3nn/e3nn-jax/assets/35970687/24efa263-0d9d-4196-812c-055895d53749)

<table>
<thead>
  <tr>
    <th></th>
    <th colspan="3">L=1</th>
    <th colspan="3">L=3</th>
    <th colspan="3">L=5</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td></td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
    <td>Frwd</td>
    <td>Bkwd</td>
    <td>Jit</td>
  </tr>
  <tr>
    <td>0.17.3</td>
    <td>8.76</td>
    <td>12.54</td>
    <td>281.73</td>
    <td>28.12</td>
    <td>40.30</td>
    <td>646.79</td>
    <td>48.02</td>
    <td>99.25</td>
    <td>1192.13</td>
  </tr>
  <tr>
    <td>0.19.1</td>
    <td>8.68</td>
    <td>14.34</td>
    <td>616.73</td>
    <td>23.19</td>
    <td>211.03</td>
    <td>4865.74</td>
    <td>43.72</td>
    <td>667.66</td>
    <td>30524.66</td>
  </tr>
  <tr>
    <td>0.19.2</td>
    <td>24.08</td>
    <td>28.08</td>
    <td>2387.04</td>
    <td>28.18</td>
    <td>324.11</td>
    <td>9087.49</td>
    <td>40.97</td>
    <td>959.80</td>
    <td>56982.16</td>
  </tr>
  <tr>
    <td>0.20.0</td>
    <td>24.51</td>
    <td>16.37</td>
    <td>2054.15</td>
    <td>28.03</td>
    <td>156.77</td>
    <td>4349.48</td>
    <td>34.83</td>
    <td>459.85</td>
    <td>9607.55</td>
  </tr>
  <tr>
    <td>0.20.1</td>
    <td><b>23.32</td>
    <td>12.87</td>
    <td>1694.26</td>
    <td>29.97</td>
    <td>32.96</td>
    <td>2709.91</td>
    <td>31.10</td>
    <td>50.55</td>
    <td>3579.64</td>
  </tr>
</tbody>
</table>


As for the other question I would say it is a good approximation: segnn is of course more involved but runtimes should be closely related, the main difference being `IrrepsArray` operations here and there in segnn. Most of the compute is spent in the tensor products anyway.

To me it looks like backward runtime is back to normal (or better). I'm leaving the issue open in case you want to address the _L=1 forward_ thing. Thanks again for your work.

**Comment by mariogeiger** [comment]
@gerkone  please reopen this issue in case
