### ISSUE TITLE
Availability of FullTensorProduct function similar to PyTorch version

### ISSUE THREAD

**Issue by tai-dang11** [e3nn/e3nn-jax#43]
Hello,

I've been using the FullTensorProduct function in the PyTorch version of e3nn and found it very beneficial. As I'm transitioning to JAX and Haiku, I was exploring e3nn-jax and couldn't locate a similar function.

Is there an equivalent to FullTensorProduct in the JAX version? If not, are there plans to add it?

Thank you for your great work on this library.

**Comment by mariogeiger** [comment]
`FullTensorProduct` is now named `tensor_product` 


😂

**Comment by tai-dang11** [comment]
I see. Thank you so much.
