### ISSUE TITLE
FullyConnectedTensorProduct Feature Discrepancy in JAX vs. Torch

### ISSUE THREAD

**Issue by tai-dang11** [e3nn/e3nn-jax#44]
In the PyTorch's FullyConnectedTensorProduct, there's an option to set internal_weights to False. I couldn't find a similar feature in JAX. Also, I'm curious if JAX and Haiku allow using predefined weights for this operation. If I'm overlooking something or if I'm incorrect, please correct me. If not, integrating these features would be great.

**Comment by mariogeiger** [comment]
Hi

Please ask your questions in the discussions. 

Two independent notes about your question:

- FullyConnectedTensorProduct is equivalent to tensor_product followed by Linear. 

- Using haiku you can provide the parameters externally for a model. I'll try to find you an example if I have time

**Comment by tai-dang11** [comment]
Hi, Thank you for answering. I'll follow up with you on discussions
