### ISSUE TITLE
migrate to `pyproject.toml` for packaging 

### ISSUE THREAD

**Issue by SauravMaheshkar** [e3nn/e3nn-jax#53]
`pyproject.toml` is the new standard for packaging python packages, `setup.py` is now deprecated (first introduced in [PEP 518](https://peps.python.org/pep-0518/) and later expanded in [PEP 517](https://peps.python.org/pep-0517/), [PEP 621](https://peps.python.org/pep-0621/) and [PEP 660](https://peps.python.org/pep-0660/)).

Shifting to a `pyproject.toml` based build would lead to a much simpler project structure (a single `pyproject.toml` as opposed to `setup.py` + `pyproject.toml` + `requirements-dev.txt`).

Nothing much would change for the end user, the way to install the package still remains the same. The only minimal change would be to use `python -m build`.

I'm happy to take this up 😄 

References:

* A similar PR was accepted to pytorch-geometric which now only relies on a `pyproject.toml` based build system. https://github.com/pyg-team/pytorch_geometric/pull/6880

**Comment by mariogeiger** [comment]
Hi,
I would be very happy. I already have an attempt of that so feel free to suggest modifications.
