### ISSUE TITLE
refactor test suite

### ISSUE THREAD

**Issue by SauravMaheshkar** [e3nn/e3nn-jax#55]
I'd like to suggest a refactoring of the current test suite. Having all tests under the `tests/` directory which follows the same pattern as the module. i.e.

```
e3nn_jax/
 ...
tests/
 noxfile.py
 conftest.py
 ...
```

A lot of modern JAX based frameworks follow the same structure, viz flax, jax-md, jax (itself) and kfac-jax.

**Comment by mariogeiger** [comment]
Sounds good to me
