### ISSUE TITLE
GitHub install fails silently

### ISSUE THREAD

**Issue by ameya98** [e3nn/e3nn-jax#61]
Installing from GitHub used to work:
```bash
pip install git+https://github.com/e3nn/e3nn-jax
```
but now
```python
import e3nn_jax
```
raises an ImportError.

**Comment by mariogeiger** [comment]
@SauravMaheshkar any idea?

**Comment by SauravMaheshkar** [comment]
Hey 👋🏽 , I quickly spun up a Google Colab and tried it out, it works fine on Colab.

* [Colab Notebook](https://colab.research.google.com/drive/1mscO9-FYLGSV9LS7u1v3k2KAKgDh1Fko?usp=sharing)

**Comment by ameya98** [comment]
This might have been something messed up in my environment. I made a new one and it seems to work now. Sorry for the inconvenience!
