### ISSUE TITLE
TensorProduct and FullyConnectedTensorProduct in e3nn_jax

### ISSUE THREAD

**Issue by VinaySingh561** [e3nn/e3nn-jax#67]
Hi, Do we have equivalent of e3nn.o3.TensorProduct and e3nn.o3.FullyConnectedTensorProduct [torch version] in e3nn_jax? I am attaching the code here for your reference, which is being taken from [here](https://github.com/e3nn/e3nn/blob/41c184cc4b782dd6215e9054a8c5ffa9ebe7fb92/e3nn/nn/models/gate_points_2101.py)

`self.sc = FullyConnectedTensorProduct(self.irreps_in, self.irreps_node_attr, self.irreps_out)

        self.lin1 = FullyConnectedTensorProduct(self.irreps_in, self.irreps_node_attr, self.irreps_in)

        irreps_mid = []
        instructions = []
        for i, (mul, ir_in) in enumerate(self.irreps_in):
            for j, (_, ir_edge) in enumerate(self.irreps_edge_attr):
                for ir_out in ir_in * ir_edge:
                    if ir_out in self.irreps_out:
                        k = len(irreps_mid)
                        irreps_mid.append((mul, ir_out))
                        instructions.append((i, j, k, 'uvu', True))
        irreps_mid = o3.Irreps(irreps_mid)
        irreps_mid, p, _ = irreps_mid.sort()

        instructions = [
            (i_1, i_2, p[i_out], mode, train)
            for i_1, i_2, i_out, mode, train in instructions
        ]

        tp = TensorProduct(
            self.irreps_in,
            self.irreps_edge_attr,
            irreps_mid,
            instructions,
            internal_weights=False,
            shared_weights=False,
        )
        self.fc = FullyConnectedNet([number_of_basis] + radial_layers * [radial_neurons] + [tp.weight_numel], torch.nn.functional.silu)
        self.tp = tp

        self.lin2 = FullyConnectedTensorProduct(irreps_mid, self.irreps_node_attr, self.irreps_out)
`

Thanks for your help.

**Comment by ameya98** [comment]
Check out https://github.com/e3nn/e3nn-jax/discussions/50.
