### ISSUE TITLE
Improve test coverage.

### ISSUE THREAD

**Issue by ameya98** [e3nn/e3nn-jax#9]
Starting with [core_tensor_product.py](https://github.com/e3nn/e3nn-jax/blob/main/e3nn_jax/_core_tensor_product.py)!

**Comment by ameya98** [comment]
@mariogeiger what is the difference between `tests/tensor_product_test.py` and `tests/core_tensor_product_test copy.py`? Is this copy supposed to be committed?

**Comment by mariogeiger** [comment]
Haha the " copy" is a mistake indeed. But the two files test different things. The "core" test the basic TP class while the other file test the subclasses made out of the basic class.
